[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- CẤU HÌNH TỐC ĐỘ ---
monitor_speed = 115200
upload_speed = 921600

; --- CẤU HÌNH BỘ NHỚ (Cho bản N16R8) ---
; Flash 16MB
board_upload.flash_size = 16MB
; Partition table (Chia bộ nhớ để chứa code AI lớn)
board_build.arduino.partitions = default_16MB.csv
; Chế độ Flash & PSRAM (OPI cho tốc độ cao nhất)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

; --- CÁC FLASH QUAN TRỌNG ---
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0  ; Dùng UART qua CH343 (COM12)
    -DARDUINO_USB_MODE=1

lib_deps =
    fastled/FastLED